### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher-micro-frontend-experiment#4]
> Hard to share caches between the different services, unless something like Varnish is run locally?

> Even more API requests [with component-level frontends]...

**Comment by thewilkybarkid** [comment]
For eLife we used caching at the code level, with it stored in Redis. The implementation is pretty basic, and isn't shared.

Might be an idea to run a Varnish in front of each back-end service, and allow private caching. This needs care, and can easily be optional for basic usage.

**Comment by giorgiosironi** [comment]
As long as the architecture is sympathetic to using HTTP correctly, this looks like a deferrable decision?

**Comment by thewilkybarkid** [comment]
Yep; extending it to _private_ caching is the other thing to bear in mind.

**Comment by thewilkybarkid** [comment]
The other aspect is the front-end, which is being covered by https://github.com/libero/publisher-micro-frontend-experiment/issues/3.

Will close this.
